---
- name: Import AWS playbook
  ansible.builtin.import_playbook: aws.yml

- name: Import base image playbook
  ansible.builtin.import_playbook: base.yml

- name: Import UFW playbook
  ansible.builtin.import_playbook: ufw.yml

- name: Import Docker playbook
  ansible.builtin.import_playbook: docker.yml

# The AWS and Docker playbooks must run before this one, since this
# playbook uses user groups created in those playbooks.
- name: Import VNC playbook
  ansible.builtin.import_playbook: vnc.yml

# The VNC playbook must run before this one, since this playbook uses
# a user created in the VNC playbook.
- name: Import Xfce playbook
  ansible.builtin.import_playbook: xfce.yml

- name: Import cloud-init playbook
  ansible.builtin.import_playbook: cloud_init.yml
