---
- name: Import base image playbook
  import_playbook: base.yml

- name: Import UFW playbook
  import_playbook: ufw.yml

- name: Import Docker playbook
  import_playbook: docker.yml

- name: Import VNC playbook
  import_playbook: vnc.yml

- name: Import AWS playbook
  import_playbook: aws.yml
